# Site settings
title: "Raushan Singh"
description: "Raushan Singh's webpage"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Raushan Singh"
resume_title:                   "Software Engineer | Microsoft | IIT Guwahati"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "raushansingh1401@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "7002796605"
resume_contact_address:         "Girja Niwas, Jalla Gali, Patna city, Patna - 800008, Bihar, India"

resume_header_contact_info:     "7002796605 • raushansingh1401@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Software Engineer with 4+ years of experience at Microsoft and Samsung R&D, specializing in backend development, distributed systems, and mobile application development. Strong expertise in C++, Python, Java, and Swift, with hands-on experience in API design, cloud security solutions, automation testing, and UI development. Passionate about designing scalable, high-performance applications.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/raushansingh1401"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/raushansingh1401/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
